# Validate the vendored snapshot without requiring a sibling ttpcomm checkout.
get_filename_component(_ttp_sdk_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(READ "${_ttp_sdk_root}/SDK_MANIFEST.json" _ttp_sdk_manifest)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_ttp_sdk_root}/SDK_MANIFEST.json")
string(JSON _ttp_sdk_count LENGTH "${_ttp_sdk_manifest}" files)
math(EXPR _ttp_sdk_last "${_ttp_sdk_count} - 1")
foreach(_ttp_sdk_index RANGE 0 ${_ttp_sdk_last})
  string(JSON _ttp_sdk_name MEMBER "${_ttp_sdk_manifest}" files ${_ttp_sdk_index})
  string(JSON _ttp_sdk_expected GET "${_ttp_sdk_manifest}" files "${_ttp_sdk_name}")
  file(READ "${_ttp_sdk_root}/${_ttp_sdk_name}" _ttp_sdk_source)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_ttp_sdk_root}/${_ttp_sdk_name}")
  string(REPLACE "\r\n" "\n" _ttp_sdk_source "${_ttp_sdk_source}")
  string(SHA256 _ttp_sdk_actual "${_ttp_sdk_source}")
  if(NOT _ttp_sdk_actual STREQUAL _ttp_sdk_expected)
    message(FATAL_ERROR "ttpcomm SDK snapshot differs: ${_ttp_sdk_name}; re-export with ttpcomm/cmake/sync_sdk.py")
  endif()
endforeach()
